### PR TITLE
Change Key Scopes to Base Scope

### PR DESCRIPTION
**Pull request by mountainraptor**
Allow UI access to manage keys
Add check to make sure if key added is already in keysdir to not
copy again (causes zero file size)

### CODE REVIEW

**Comment by mountainraptor** [comment]
**Allow the keys to be part of the base scope:** Are there security concerns here for client side requests for keys? It appears that base-auth is not required to list, however it is required for the auth-token to create a key.
**Create its own read/write scope:** Does an additional scope add complexity without benefit?
**Make the module that wants this set up its own end points in MC:** This sounds like it could lead to fragmented code. Since keys are part of BITS base and required for modules, logs, etc, abdicating control on a per-module basis could lead to multiple access methods for keys that could be rebroadcast

**Comment by nbroeking** [comment]
My concerns are that as follows for security. 

Modules are currently given full trust on the server side because currently only the provisioner can add keys. Users can then only add modules if the original provisioner has signed them. Adding the ability for users to modify the keys gives them the ability to upload any module they want. Which then should make it so that modules are not always trusted on the server. 

Does that make sense?

I think that there somehow needs the ability to modify keys but I think we need to evaluate how to protect the box while doing so. Thoughts? @mountainraptor @Sha-Bang @bschmickley @KevinDyer  @mokus0

**Comment by mountainraptor** [comment]
Changes were made to the key-management module to work within the current BITS scope. It now loads and can manage keys without changing the scope to the base scope.

**Comment by mountainraptor** [comment]
Closing pull request.

**Pull request closed without merging**
