### PR TITLE
initial start to Docker support for bits

### PR DESCRIPTION
**Pull request by maihde**
This commit adds a Dockerfile, some instructions in the README, and a few helper scripts in package.json.

### CODE REVIEW

**Comment by nbroeking** [comment]
@nanpx @KevinDyer 
I agree. I would love to see a different repo that allowed for this. It should be split out from the base though.

**Comment by maihde** [comment]
Splitting it out sounds good as well.  That approach lets you easily build multiple version.  If you want me to create a first stab at what this would look like, let me know.

In the interim, I found that the repository actually had an old support/development/docker/ folder so that is where I placed the updated copy.

**Comment by nanpx** [comment]
@maihde, I'll see what we can do to get the docker repo set up this week

**Comment by maihde** [comment]
Thanks Matt!  Let me know how I can help.

**Comment by nbroeking** [comment]
I am going to close this. I think the consensus is to create a bits docker repo

**Pull request closed without merging**
