### PR TITLE
Minor changes to README and installation

### PR DESCRIPTION
**Pull request by maihde**

### CODE REVIEW

**Comment by nanpx** [comment]
I think we should actually remove the commands on how to install nodejs. It would probably be best to just link directly to the downloads page (https://nodejs.org/en/download/) and let the user decide how to install. Same for Yarn (https://yarnpkg.com/lang/en/docs/install/) although we should mention that yarn should not be installed via npm.

**Comment by maihde** [comment]
Keeping or removing Node installation from the README is your call, I don't have an opinion there.  If you assume that Node is already installed, the original README provides the following guidance:

```
npm run build
npm install yarn
```

The first will fail, because none of the other node modules have been installed.  I changed it to:

```
npm install
npm run build
```

Which works for me.  To make things easier I added Yarn into the devDependencies, but it sounds like there is a desire to have users install Yarn separately which is fine as long as the README indicates that.

On a side note, I added another commit fixing the ChildProcess documentation.  I can put that into a separate pull request if you prefer.

**Comment by nanpx** [comment]
Good catch on the ChildProcess, let's remove the yarn dependency from devDependencies and call out that both node and yarn will need to be installed prior to installing bits, providing links to the download and install pages on each site.

**Comment by maihde** [comment]
I'm going to close this pull request and create new ones that separate the two issues.  I've also recently prepared a Docker image for bits which I will make a pull request for as well.

**Comment by nanpx** [comment]
@maihde, we might want to do a separate repository for the docker image, something similar to what we've already done with [bits-vagrant](https://github.com/LGSInnovations/bits-vagrant).

@KevinDyer do you want to set that up?

**Comment by maihde** [comment]
so the Docker only requires one file, so it seems overkill at this point to create a separate repository, but ultimately it's your call.  You can see my progress to date here https://github.com/Axios-Engineering/bits/tree/add-docker-support.

**Pull request closed without merging**
